feat-scss
jazzcodes/ProductivityZap pull request #4
Opened 2023-05-12 08:03 UTC by jazzcodes

Configured SCSS

2023-05-21 13:46 UTC, mandeeps708 requested changes

2023-05-21 13:46 UTC, mandeeps708 commented on .eslintrc.json
> +      "no-console": "off"
Let's turn it on.

2023-05-21 13:46 UTC, mandeeps708 commented on css/styles.css
> +  box-sizing: border-box; }
The closing brace should be in new line. 

Are you following some standard for this?

But if you have shifted to scss, then we can skip making changes to this.

2023-05-24 04:45 UTC, mandeeps708 commented
@jazzcodes Can you close this PR as #5 has all this code.

2023-05-24 05:19 UTC, jazzcodes commented
PR #5 has all this code.

2023-05-24 05:19 UTC, closed without merging